<?php
/* @var \Codilar\HelloWorld\Block\Hello $block */
?>
<label><?= __("Sample Data retrieved from this Block is ") ?></label>
<h1><?= $block->getText() ?></h1>
<h1><?= $block->getData('sku') ?></h1>
<h1><?= $block->getTaxClass() ?></h1>
<h1><?= $block->getAnimal() ?></h1>
<h1><?= $block->getClass() ?></h1>
<?php $bc = $block->getBlockClass()  ?>
<h1><?= $bc->getSportsProduct() ?></h1>
<?php $mc = $block->getModelClass()  ?>
<h1><?= $mc->getCustomMethod() ?></h1>

