<?php
?>
<label><?= __("Block two ") ?></label>
<div style="color:blue"><?=  __("Doods and I were headed to the place where Lola’s story began, up north in the central plains: Tarlac province. Rice country. The home of a cigar-chomping army lieutenant named Tomas Asuncion, my grandfather. The family stories paint Lieutenant Tom as a formidable man given to eccentricity and dark moods, who had lots of land but little money and kept mistresses in separate houses on his property. His wife died giving birth to their only child, my mother. She was raised by a series of utusans, or people who take commands.") ?></div>
