<?php
/** @var \Wellevate\Logger\Block\Index $block */
?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('System Log Files') ?></span>
        </div>
        <div class="admin__page-section-item-content section-config">
            <table class="admin__table-primary">
                <tr>
                    <th>Filename</th>
                    <th>Directory</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                    <th></th>
                </tr>
                <?php
                try {
                    $logFiles = $block->getSystemFiles();
                } catch (Exception $e) {

                }
                ?>
                <?php foreach ($logFiles as $log) { ?>
                    <tr>
                        <td>
                            <a href="<?php echo $block->downloadSystemFile($log['name'], 'log'); ?>"><?php echo $log['name'] ?></a>
                        </td>
                        <td>var/log</td>
                        <td><?php echo $log['filesize'] ?></td>
                        <td><?php echo $log['modTimeLong'] ?></td>
                        <td>
                            <span class="action-children">
                                <a href="<?php echo $block->previewSystemFile($log['name'], 'log'); ?>"
                                   class="icon-view">View</a> |
                            </span>
                            <span class="action-children">
                                <a
                                        href="<?php echo $block->downloadSystemFile($log['name'], 'log'); ?>"
                                        class="icon-export">Download</a>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
            </table>

        </div>

        <br> <br>

        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('System Report Files') ?></span>
        </div>
        <div class="admin__page-section-item-content section-config">
            <table class="admin__table-primary">
                <tr>
                    <th>Filename</th>
                    <th>Directory</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                    <th></th>
                </tr>
                <?php
                try {
                    $reportFiles = $block->getSystemFiles('report');
                } catch (Exception $e) {

                }
                ?>
                <?php foreach ($reportFiles as $log) { ?>
                    <tr>
                        <td>
                            <a href="<?php echo $block->downloadSystemFile($log['name'], 'report'); ?>"><?php echo $log['name'] ?></a>
                        </td>
                        <td>var/report</td>
                        <td><?php echo $log['filesize'] ?></td>
                        <td><?php echo $log['modTimeLong'] ?></td>
                        <td>
                            <span class="action-children">
                                <a href="<?php echo $block->previewSystemFile($log['name'], 'report'); ?>"
                                   class="icon-view">View</a> |
                            </span>
                            <span class="action-children">
                                <a
                                        href="<?php echo $block->downloadSystemFile($log['name'], 'report'); ?>"
                                        class="icon-export">Download</a>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <br> <br>

        <br> <br>

        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('API Report Files') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-primary">
                <tr>
                    <th>Filename</th>
                    <th>Directory</th>
                    <th>Size</th>
                    <th>Last Modified</th>
                    <th></th>
                </tr>
                <?php
                try {
                    $apiReportFiles = $block->getSystemFiles('report' . DIRECTORY_SEPARATOR . 'api');
                } catch (Exception $e) {

                }
                ?>
                <?php foreach ($apiReportFiles as $log) { ?>
                    <tr>
                        <td>
                            <a href="<?php echo $block->downloadSystemFile($log['name'], 'report'); ?>"><?php echo $log['name'] ?></a>
                        </td>
                        <td>var/report/api</td>
                        <td><?php echo $log['filesize'] ?></td>
                        <td><?php echo $log['modTimeLong'] ?></td>
                        <td>
                            <span class="action-children">
                                <a href="<?php echo $block->previewSystemFile($log['name'], 'report' . DIRECTORY_SEPARATOR . 'api'); ?>"
                                   class="icon-view">View</a> |
                            </span>
                            <span class="action-children">
                                <a
                                        href="<?php echo $block->downloadSystemFile($log['name'], 'report' . DIRECTORY_SEPARATOR . 'api'); ?>"
                                        class="icon-export">Download</a>
                            </span>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <br> <br>

    </div>
</section>